# ZAP Baseline Configuration
# Format: key<TAB>value

exclude \.css$
exclude \.js$
exclude \.png$
exclude \.jpg$
exclude \.ico$

scanners    all
levels  I,H,M,L

connectionTimeout   30
ioTimeout   120
