apiVersion: v1
kind: Service
metadata:
  name: workout-app-service
  namespace: workout-namespace
spec:
  selector:
    app: workout-app
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
